linters-settings:
  dupl:
    threshold: 175
  funlen:
    lines: 150
    statements: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 25
  lll:
    line-length: 250
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - unused
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - govet
    - lll
    - misspell
    - nakedret
    - nolintlint
    - copyloopvar
    - typecheck
    - unconvert
    - whitespace

issues:
  exclude-dirs:
    - tests
    - tools
    - vendor

run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 5
  tests: true
  go: "1.25"
