project_name: dctl

before:
  hooks:
    - go mod tidy

builds:
  - binary: "{{.ProjectName}}"
    dir: ./cmd/cli
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -s -w -X main.commit={{.ShortCommit}}
      - -s -w -X main.date={{.CommitDate}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7

release:
  github:
    owner: mchmarny
    name: dctl
  prerelease: auto

archives:
  - format: binary
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: "checksums-sha256.txt"

snapshot:
  name_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - readme
      - typo

brews:
  -
    goarm: 7
    tap:
      owner: mchmarny
      name: homebrew-dctl
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/mchmarny/dctl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: github-actions
      email: github-actions@github.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/mchmarny/dctl"
    description: "Simple utility to provide insight into repo activity."
    license: "Apache-2.0"
    # test: |
    #   system "#{bin}/dctl --version"
    #   ...

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    # install: |
    #   bin.install "dctl"
    #   ...

