version: 2

project_name: devpulse

builds:
  - binary: "{{.ProjectName}}"
    dir: ./cmd/devpulse
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
        -X github.com/mchmarny/devpulse/pkg/cli.version={{.Version}}
        -X github.com/mchmarny/devpulse/pkg/cli.commit={{.ShortCommit}}
        -X github.com/mchmarny/devpulse/pkg/cli.date={{.CommitDate}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7

release:
  github:
    owner: mchmarny
    name: devpulse
  prerelease: auto

archives:
  - formats:
      - binary
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: "checksums-sha256.txt"

sboms:
  - artifacts: binary

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

report_sizes: true

snapshot:
  version_template: "{{.Tag}}-next"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^build:"
      - "^ci:"
      - "^style:"
      - typo
      - readme

brews:
  -
    goarm: 7
    repository:
      owner: mchmarny
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/mchmarny/devpulse/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: github-actions
      email: github-actions@github.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/mchmarny/devpulse"
    description: "Simple utility to provide insight into repo activity."
    license: "Apache-2.0"
