name: 'Setup Go Environment'
description: 'Configure Go toolchain from go.mod'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
      with:
        go-version-file: go.mod
