name: 'Setup Go Environment'
description: 'Configure Go toolchain from go.mod'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5  # v6.2.0
      with:
        go-version-file: go.mod
