sources:
  - org: NVIDIA
    repos:
      - aicr
      - DCGM
      - dcgm-exporter
      - gpu-operator
      - k8s-device-plugin
      - kubevirt-gpu-device-plugin
      - nvidia-container-toolkit
      - NVSentinel
      - skyhook
score:
  count: 100
