# Scores PR author reputation using mchmarny/reputer action.
name: reputation

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  reputation:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: mchmarny/reputer@71a4aeefc09189a0a0df7f45e4223426162fc213  # pinned
        with:
          trusted-orgs: |
            mchmarny
